/**
 * PDF export logic for reports
 */

import { MONTHS_EN } from '../types';

export async function exportPdfReport(
  selectedMonth: number,
  selectedYear: number,
  totalRevenue: number,
  paidCount: number,
  overdueCount: number,
  reportData: any[]
) {
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Header
  doc.setFillColor(30, 30, 30);
  doc.rect(0, 0, 210, 38, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('PrimeRent', 15, 16);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Monthly Revenue Report', 15, 25);
  doc.text(`${MONTHS_EN[selectedMonth]} ${selectedYear}`, 15, 33);

  // Stats summary boxes
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');

  const statsY = 48;
  // Box 1 — Total Revenue
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(10, statsY, 58, 24, 3, 3, 'F');
  doc.setTextColor(30, 30, 30);
  doc.text('Total Revenue', 15, statsY + 9);
  doc.setFontSize(14);
  doc.text(`THB ${totalRevenue.toLocaleString()}`, 15, statsY + 19);

  // Box 2 — Paid
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(72, statsY, 58, 24, 3, 3, 'F');
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.text('Paid Tenants', 77, statsY + 9);
  doc.setFontSize(14);
  doc.text(`${paidCount} / ${reportData.length}`, 77, statsY + 19);

  // Box 3 — Overdue
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(134, statsY, 66, 24, 3, 3, 'F');
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.text('Overdue', 139, statsY + 9);
  doc.setFontSize(14);
  doc.text(`${overdueCount} tenant(s)`, 139, statsY + 19);

  // Table
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Transaction Details', 10, statsY + 36);

  autoTable(doc, {
    startY: statsY + 40,
    head: [['Tenant', 'Property', 'Amount (THB)', 'Date', 'Status', 'Ref. ID']],
    body: reportData.map(r => [
      r.tenant, r.property, `฿${r.amount.toLocaleString()}`, r.date, r.status, r.ref
    ]),
    headStyles: { fillColor: [30, 30, 30], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: [248, 250, 255] },
    columnStyles: { 2: { halign: 'right' }, 4: { halign: 'center' } },
    margin: { left: 10, right: 10 },
    didParseCell: (data) => {
      if (data.column.index === 4 && data.section === 'body') {
        const val = data.cell.raw as string;
        data.cell.styles.textColor = val === 'ชำระแล้ว' ? [30, 30, 30] : [30, 30, 30];
        data.cell.styles.fontStyle = 'bold';
      }
    }
  });

  // Footer
  const pageH = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by PrimeRent System — ${new Date().toLocaleDateString('th-TH')}`, 10, pageH - 8);
  doc.text('Confidential — For property owner use only.', 10, pageH - 4);

  doc.save(`PrimeRent_Report_${MONTHS_EN[selectedMonth]}_${selectedYear}.pdf`);
}
