'use client';

import React, { useState, useEffect } from 'react';
import type { Language } from '@/lib/types';
import { useUser } from '@/firebase';
import { toast } from '@/hooks/use-toast';
import { SystemPreferences } from './SystemPreferences';
import { PDPAControls } from './PDPAControls';
import { DataPortability } from './DataPortability';
import { SimulatedEmailInbox } from './SimulatedEmailInbox';

interface TabPreferencesProps {
  lang: Language;
}

export function TabPreferences({ lang }: TabPreferencesProps) {
  const isTh = lang === 'th';
  const { user } = useUser();

  const [marketingConsent, setMarketingConsent] = useState(true);
  const [analyticsConsent, setAnalyticsConsent] = useState(false);

  useEffect(() => {
    const savedMarketing = localStorage.getItem('primerent_pdpa_marketing');
    const savedAnalytics = localStorage.getItem('primerent_pdpa_analytics');
    if (savedMarketing !== null) setMarketingConsent(savedMarketing === 'true');
    if (savedAnalytics !== null) setAnalyticsConsent(savedAnalytics === 'true');
  }, []);

  const handleConsentToggle = (type: 'marketing' | 'analytics', value: boolean) => {
    if (type === 'marketing') {
      setMarketingConsent(value);
      localStorage.setItem('primerent_pdpa_marketing', String(value));
    } else {
      setAnalyticsConsent(value);
      localStorage.setItem('primerent_pdpa_analytics', String(value));
    }
    toast({
      title: isTh ? 'บันทึกความยินยอมส่วนตัวสำเร็จ' : 'Consent Preferences Updated',
      description: isTh ? 'ความประสงค์ของคุณได้รับการอัปเดตเข้าระบบฐานข้อมูล' : 'Your preferences have been logged.'
    });
  };

  const handleWithdrawAll = () => {
    setMarketingConsent(false);
    setAnalyticsConsent(false);
    localStorage.setItem('primerent_pdpa_marketing', 'false');
    localStorage.setItem('primerent_pdpa_analytics', 'false');
    toast({
      title: isTh ? 'ถอนความยินยอมความปลอดภัยแล้ว' : 'Consents Withdrawn',
      description: isTh ? 'ลบความยินยอมทางเลือกเสริมทั้งหมดเรียบร้อยแล้ว' : 'All optional privacy consents are now turned off.'
    });
  };

  const handleDataPortabilityPDF = async () => {
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(22);
      doc.text("PERSONAL DATA EXPORT REPORT (PDPA)", 105, 20, { align: "center" });
      
      doc.setFontSize(9);
      doc.setFont("Helvetica", "normal");
      doc.text(`Generated Date: ${new Date().toLocaleString()}`, 105, 26, { align: "center" });
      doc.text(`Compliance: Thailand PDPA / GDPR Standard`, 105, 31, { align: "center" });

      doc.line(20, 37, 190, 37);

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(13);
      doc.text("1. ACCOUNT USER PROFILE DATA", 20, 48);
      
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`UID: ${user?.uid || 'MOCK_USER_123456'}`, 25, 56);
      doc.text(`Name: ${user?.displayName || 'Jane Doe'}`, 25, 62);
      doc.text(`Email Address: ${user?.email || 'user@example.com'}`, 25, 68);
      doc.text(`Email Verified: ${user?.emailVerified ? 'Yes' : 'No'}`, 25, 74);
      doc.text(`Is Mock Account: ${user?.isMock ? 'Yes (Sandbox)' : 'No (Live)'}`, 25, 80);

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(13);
      doc.text("2. DATA PROCESSING CONSENT LOGS", 20, 95);
      
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Necessary Personal Data Processing: ACTIVE (Required for rental services)`, 25, 103);
      doc.text(`Marketing & Promotions Consent: ${marketingConsent ? 'GRANTED' : 'DENIED'}`, 25, 109);
      doc.text(`Third-Party Analytics Consent: ${analyticsConsent ? 'GRANTED' : 'DENIED'}`, 25, 115);

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(13);
      doc.text("3. SECURITY AND PRIVACY STATEMENTS", 20, 130);
      
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      
      const statement = `This export represents a snapshot of your personal data stored within the PrimeRent platform databases. You hold the right to ask for modification (Rectification), restriction of data processing, or complete removal (Erasure - Right to be forgotten) by sending a request to privacy@primerent.com.`;
      
      const splitText = doc.splitTextToSize(statement, 160);
      doc.text(splitText, 25, 138);

      doc.setTextColor(150, 150, 150);
      doc.text("Generated by PrimeRent Automated Privacy Agent. Secured via client-side PDF build.", 105, 275, { align: "center" });

      doc.save(`PDPA_Personal_Data_Export.pdf`);

      toast({
        title: isTh ? 'ส่งออกข้อมูลสำเร็จ' : 'Data Export Success',
        description: isTh ? 'ดาวน์โหลดไฟล์ข้อมูลส่วนบุคคล PDPA เป็น PDF แล้ว' : 'Your personal data export PDF is ready.'
      });
    } catch (err: any) {
      console.error(err);
      toast({
        variant: 'destructive',
        title: 'Export Failed',
        description: err.message
      });
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-500 font-thai">
      <SystemPreferences isTh={isTh} />
      <PDPAControls 
        marketingConsent={marketingConsent}
        analyticsConsent={analyticsConsent}
        isTh={isTh}
        handleConsentToggle={handleConsentToggle}
      />
      <DataPortability 
        isTh={isTh}
        handleWithdrawAll={handleWithdrawAll}
        handleDataPortabilityPDF={handleDataPortabilityPDF}
      />
      <SimulatedEmailInbox lang={lang} />
    </div>
  );
}
