import { type AgentProfile } from './types';

export const MOCK_AGENTS: AgentProfile[] = [
  {
    uid: 'agent-001',
    displayName: 'คุณอรุณ สว่างใจ',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agent001',
    phoneNumber: '081-234-5678',
    lineId: '@arun.agent',
    tier: 'platinum',
    rating: 4.9,
    responseRate: 0.97,
    avgResponseMinutes: 8,
    serviceAreas: ['สุขุมวิท', 'อโศก', 'ทองหล่อ', 'พร้อมพงษ์', 'เอกมัย'],
    specialties: ['condo', 'apartment'],
    activeJobs: 2,
    maxJobs: 5,
    isAvailable: true,
    experienceYears: 8,
    totalDeals: 342,
  },
  {
    uid: 'agent-002',
    displayName: 'คุณมณี รุ่งเรือง',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agent002',
    phoneNumber: '082-345-6789',
    lineId: '@manee.re',
    tier: 'gold',
    rating: 4.7,
    responseRate: 0.93,
    avgResponseMinutes: 12,
    serviceAreas: ['ลาดพร้าว', 'รัชดา', 'ห้วยขวาง', 'พระราม 9', 'อโศก'],
    specialties: ['condo', 'house', 'townhouse'],
    activeJobs: 1,
    maxJobs: 4,
    isAvailable: true,
    experienceYears: 5,
    totalDeals: 198,
  },
  {
    uid: 'agent-003',
    displayName: 'คุณวิชัย ดีใจ',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agent003',
    phoneNumber: '083-456-7890',
    lineId: '@wichai.d',
    tier: 'gold',
    rating: 4.6,
    responseRate: 0.90,
    avgResponseMinutes: 15,
    serviceAreas: ['สาทร', 'สีลม', 'บางรัก', 'ยานนาวา', 'คลองเตย'],
    specialties: ['condo', 'apartment'],
    activeJobs: 3,
    maxJobs: 5,
    isAvailable: true,
    experienceYears: 6,
    totalDeals: 215,
  },
  {
    uid: 'agent-004',
    displayName: 'คุณสุดา พอดีดี',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agent004',
    phoneNumber: '084-567-8901',
    lineId: '@suda.p',
    tier: 'silver',
    rating: 4.3,
    responseRate: 0.85,
    avgResponseMinutes: 20,
    serviceAreas: ['บางนา', 'อ่อนนุช', 'อุดมสุข', 'แบริ่ง', 'สมุทรปราการ'],
    specialties: ['house', 'townhouse'],
    activeJobs: 1,
    maxJobs: 4,
    isAvailable: true,
    experienceYears: 3,
    totalDeals: 87,
  },
  {
    uid: 'agent-005',
    displayName: 'คุณธนา ฟ้าใส',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agent005',
    phoneNumber: '085-678-9012',
    lineId: '@thana.fs',
    tier: 'platinum',
    rating: 4.95,
    responseRate: 0.99,
    avgResponseMinutes: 5,
    serviceAreas: ['จตุจักร', 'อารีย์', 'สะพานควาย', 'ลาดยาว', 'รัชโยธิน'],
    specialties: ['condo', 'house', 'apartment', 'townhouse'],
    activeJobs: 4,
    maxJobs: 6,
    isAvailable: true,
    experienceYears: 12,
    totalDeals: 567,
  },
  {
    uid: 'agent-006',
    displayName: 'คุณกัลยา สมหวัง',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agent006',
    phoneNumber: '086-789-0123',
    tier: 'silver',
    rating: 4.2,
    responseRate: 0.82,
    avgResponseMinutes: 25,
    serviceAreas: ['มีนบุรี', 'คลองสาน', 'ลาดกระบัง', 'หนองจอก'],
    specialties: ['house', 'townhouse'],
    activeJobs: 0,
    maxJobs: 3,
    isAvailable: true,
    experienceYears: 2,
    totalDeals: 43,
  },
];
